import { MoneyNode, NegativeEventNode, BusinessProcessNode, BusinessFunctionNode, ItServiceNode, ItResourceNode } from "./nodes";

export default [
	new MoneyNode({
		name: 'Деньги',
		id: 200,
		parents: [null]
	}),
	new NegativeEventNode({
		name: 'Падение эффективности проходки',
	  	id: 1,
	  	parents: [200],  
	  	calculateDamageMoney: (waitTimeTargetChildSum) => waitTimeTargetChildSum * 4260000,
	}),
	new NegativeEventNode({
		name: 'Перебур',
	  	id: 2,
	  	parents: [200],  
	  	calculateDamageMoney: (waitTimeTargetChildSum) => {
			if (waitTimeTargetChildSum > 0) {
			  	return 3750000;
			} else {
				return 0;
			}
		  },
	}),
	new NegativeEventNode({
		name: 'Простой',
	  	id: 3,
	  	parents: [200],  
	  	calculateDamageMoney: (waitTimeTargetChildSum) => waitTimeTargetChildSum * 12500000,
	}),
	new BusinessProcessNode({
		name: 'Запрос информации по новой скважине',
		id: 10,
	  	parents: [1],  
	}),
	new BusinessProcessNode({
		name: 'Подготовка секторной модели',
		id: 11,
	  	parents: [1],  
	}),
	new BusinessProcessNode({
		name: 'Подготовка геонавигационного проекта',
		id: 12,
	  	parents: [1],  
	}),
	new BusinessProcessNode({
		name: 'Сопровождение мониторинга',
		id: 13,
	  	parents: [2,3],	  	 
	}),
	new BusinessProcessNode({
		name: 'Завершение мониторинга',
		id: 14,
	  	parents: [1],
	}),

	new BusinessFunctionNode({
		name: 'Плановая траектория',
		id: 100,
		parents: [10],
		rtoTarget: 72,
   		rtoTest: 0,
	}),
	new BusinessFunctionNode({
		name: 'Маркшейдерская справка (привязка устья)',
		id: 101,
		parents: [10],
		rtoTarget: 48,
   		rtoTest: 0,
	}),
	new BusinessFunctionNode({
		name: 'Целевой пласт',
		id: 102,
		parents: [10],
		rtoTarget: 8,
   		rtoTest: 0,
	}),
	new BusinessFunctionNode({
		name: 'Экспорт скважин и скважинных данных БД',
		id: 103,
		parents: [11],
		rtoTarget: 8,
   		rtoTest: 0,
	}),
	new BusinessFunctionNode({
		name: 'Экспорт поверхностей',
		id: 104,
		parents: [11],
		rtoTarget: 48,
   		rtoTest: 0,
	}),
	new BusinessFunctionNode({
		name: 'Экспорт пластопересечений',
		id: 105,
		parents: [11],
		rtoTarget: 48,
   		rtoTest: 0,
	}),
	new BusinessFunctionNode({
		name: 'Импорт скважин и скважинных данных',
		id: 106,
		parents: [11],
		rtoTarget: 8,
   		rtoTest: 0,
	}),
	new BusinessFunctionNode({
		name: 'Импорт поверхностей',
		id: 107,
		parents: [11],
		rtoTarget: 8,
   		rtoTest: 0,
	}),
	new BusinessFunctionNode({
		name: 'Импорт пластопересечений',
		id: 108,
		parents: [11],
		rtoTarget: 8,
   		rtoTest: 0,
	}),
	new BusinessFunctionNode({
		name: 'Составление корреляционных схем по скважинам окружения',
		id: 109,
		parents: [11],
		rtoTarget: 8,
   		rtoTest: 0,
	}),
	new BusinessFunctionNode({
		name: 'Импорт плановых целей',
		id: 110,
		parents: [11],
		rtoTarget: 48,
   		rtoTest: 0,
	}),
	new BusinessFunctionNode({
		name: 'Импорт плановой траектории',
		id: 111,
		parents: [11],
		rtoTarget: 48,
   		rtoTest: 0,
	}),
	new BusinessFunctionNode({
		name: 'Проверка плановой траектории на выполнение геологических целей, геологическим построениям и оптимальности геометрии ствола',
		id: 112,
		parents: [11],
		rtoTarget: 8,
   		rtoTest: 0,
	}),
	new BusinessFunctionNode({
		name: 'Настройка отображения планшетов и карт (для формирования отчетности)',
		id: 113,
		parents: [11],
		rtoTarget: 72,
   		rtoTest: 0,
	}),
	new BusinessFunctionNode({
		name: 'Экспорт скважинных данных для геонавигационного проекта',
		id: 114,
		parents: [11],
		rtoTarget: 48,
   		rtoTest: 0,
	}),
	new BusinessFunctionNode({
		name: 'Создание нового проекта в сетевой папке',
		id: 115,
		parents: [12],
		rtoTarget: 36,
   		rtoTest: 0,
	}),
	new BusinessFunctionNode({
		name: 'Создание в проекте новых скважин',
		id: 116,
		parents: [12],
		rtoTarget: 36,
   		rtoTest: 0,
	}),
	new BusinessFunctionNode({
		name: 'Импорт данных по скважинам',
		id: 117,
		parents: [12],
		rtoTarget: 4,
   		rtoTest: 0,
	}),
	new BusinessFunctionNode({
		name: 'Импорт структурных поверхностей и контуров',
		id: 118,
		parents: [12],
		rtoTarget: 72,
   		rtoTest: 0,
	}),
	new BusinessFunctionNode({
		name: 'Настройка отображения планшетов и карт рабочей области (картожаных кривых ГИС, LWD и их граничных зачений, насыщения, литологии, траекторий, целевых точек и интервалов, элементов конструкции, пластопересечений, флюидальных контактов, структурных поверхностей)',
		id: 119,
		parents: [12],
		rtoTarget: 4,
   		rtoTest: 0,
	}),
	new BusinessFunctionNode({
		name: 'Получение первых данных с буровой',
		id: 120,
		parents: [13],
		rtoTarget: 1,
   		rtoTest: 0,
	}),
	new BusinessFunctionNode({
		name: 'Загрузка данных в профильное ПО',
		id: 121,
		parents: [13],
		rtoTarget: 1,
   		rtoTest: 0,
	}),
	new BusinessFunctionNode({
		name: 'Геологическая привязка по корреляционной схеме в Petrel',
		id: 122,
		parents: [13],
		rtoTarget: 1,
   		rtoTest: 0,
	}),
	new BusinessFunctionNode({
		name: 'Привязка фактического и синтетического каротажа в геонавигационном проекте Геонафт',
		id: 123,
		parents: [13],
		rtoTarget: 1,
   		rtoTest: 0,
	}),
	new BusinessFunctionNode({
		name: 'Формирование оперативного отчета excel Сетевые папки',
		id: 124,
		parents: [13],
		rtoTarget: 72,
   		rtoTest: 0,
	}),
	new BusinessFunctionNode({
		name: 'Формирование письма с рекомендацией на список рассылки MS Outlook Сопровождение мониторинга Непрерывное обработка (импорт в профильное ПО, обновление построений), поступающих данных',
		id: 125,
		parents: [13],
		rtoTarget: 1,
   		rtoTest: 0,
	}),
	new BusinessFunctionNode({
		name: 'Рассылка обновленных рекомендаций',
		id: 126,
		parents: [13],
		rtoTarget: 10,
   		rtoTest: 0,
	}),
	new BusinessFunctionNode({
		name: 'Архивирование электронной почты MS Outlook Подготовка финального отчета о проводке',
		id: 127,
		parents: [13],
		rtoTarget: 48,
   		rtoTest: 0,
	}),
	new BusinessFunctionNode({
		name: 'Актирование скважин',
		id: 128,
		parents: [13],
		rtoTarget: 48,
   		rtoTest: 0,
	}),
	new BusinessFunctionNode({
		name: 'Обновление статистики по пробуренным скважинам',
		id: 129,
		parents: [13],
		rtoTarget: 8,
   		rtoTest: 0,
	}),
	new ItServiceNode({
		name: 'MS Outlook работа с почтовыми сообщениями',
		id: 1001,
		parents: [100, 101, 102, 110, 111, 120, 125, 126, 127],		
	}),
	new ItServiceNode({
		name: 'ГеоБД работа пользователя с системой',
		id: 1002,
		parents: [103, 105],		
	}),
	new ItServiceNode({
		name: 'Сетевые папки обращение к сетевым папкам пользователей',
		id: 1003,
		parents: [104, 124, 128, 129],		
	}),
	new ItServiceNode({
		name: 'Petrel многопользовательская работа',
		id: 1004,
		parents: [106, 107, 108, 109, 112, 113, 114, 121, 122, 125],
	}),
	new ItServiceNode({
		name: 'Геонафт десктопное приложение',
		id: 1005,
		parents: [115, 116, 117, 118, 119, 121, 123, 125],		
	}),
	new ItServiceNode({
		name: 'Связь с буровой',
		id: 1006,
		parents: [120, 125, 126],		
	}),
	new ItResourceNode({
		name: 'Front-end сервер ГеоБД',
	  	id: 1101,
	  	parents: [1002],	 
		rtoTarget: 8,
  		rtoTest: 0,
	}),
	new ItResourceNode({
		name: 'Back-end сервер ГеоБД',
	  	id: 1102,
	  	parents: [1002],	 
		rtoTarget: 8,
  		rtoTest: 0,
	}),
	new ItResourceNode({
		name: 'Сервер баз данных ГеоБД',
	  	id: 1103,
	  	parents: [1002],	 
		rtoTarget: 8,
  		rtoTest: 0,
	}),
	new ItResourceNode({
		name: 'Front-end сервер эл почты',
	  	id: 1104,
	  	parents: [1001],	 
		rtoTarget: 8,
  		rtoTest: 0,
	}),
	new ItResourceNode({
		name: 'Сервер электронной почты',
	  	id: 1105,
	  	parents: [1001],	 
		rtoTarget: 8,
  		rtoTest: 0,
	}),
	new ItResourceNode({
		name: 'Сервер электронной почты',
	  	id: 1106,
	  	parents: [1001],	 
		rtoTarget: 8,
  		rtoTest: 0,
	}),
	new ItResourceNode({
		name: 'SMTP-шлюзы',
	  	id: 1107,
	  	parents: [1001],	 
		rtoTarget: 4,
  		rtoTest: 0,
	}),
	new ItResourceNode({
		name: 'Сервис DevSecOps',
	  	id: 1121,
	  	parents: [1002],
		rtoTarget: 8,
  		rtoTest: 0,
	}),
	new ItResourceNode({
		name: 'Сервис точного времени',
	  	id: 1122,
	  	parents: [1006],
		rtoTarget: 4,
  		rtoTest: 0,
	}),
	new ItResourceNode({
		name: 'Канал связи Кустовая площадка',
	  	id: 1108,
	  	parents: [1001, 1122],
		rtoTarget: 16,
  		rtoTest: 0,
	}),
	new ItResourceNode({
		name: 'Инфраструктура сбора и передачи данных на буровой',
	  	id: 1109,
	  	parents: [1006],	 
		rtoTarget: 16,
  		rtoTest: 0,
	}),
	new ItResourceNode({
		name: 'Рабочая станция пользователя',
	  	id: 1110,
	  	parents: [1002, 1003, 1004, 1005],	  	
		rtoTarget: 4,
  		rtoTest: 0,
	}),
new ItResourceNode({
		name: 'Инфраструктура дисковой системы',
	  	id: 1112,
	  	parents: [1003, 1101, 1102, 1103, 1104, 1105, 1106],
		rtoTarget: 12,
  		rtoTest: 0,
	}),
	new ItResourceNode({
		name: 'Анти-SPAM фильтры',
	  	id: 1113,
	  	parents: [1001],	 
		rtoTarget: 4,
  		rtoTest: 0,
	}),
	new ItResourceNode({
		name: 'Сервис WINS',
	  	id: 1114,
	  	parents: [1001],	 
		rtoTarget: 4,
  		rtoTest: 0,
	}),
	new ItResourceNode({
		name: 'Сервис DNS',
	  	id: 1115,
	  	parents: [1001],	 
		rtoTarget: 4,
  		rtoTest: 0,
	}),
	new ItResourceNode({
		name: 'Служба AD компании (авторизация пользователей)',
	  	id: 1116,
	  	parents: [1002, 1003],	  	
		rtoTarget: 8,
  		rtoTest: 0,
	}),
	new ItResourceNode({
		name: 'Инфраструктура как сервис (Виртуализация)',
	  	id: 1111,
	  	parents: [1001, 1002, 1003, 1004, 1101, 1102, 1103, 1104, 1105, 1106, 1107, 1113, 1114, 1115, 1116, 1121],
		rtoTarget: 16,
  		rtoTest: 0,
	}),
	
	new ItResourceNode({
		name: 'Сервис межсетевых экранов',
	  	id: 1117,
	  	parents: [1001, 1002, 1003, 1004, 1005],
		rtoTarget: 8,
  		rtoTest: 0,
	}),
	new ItResourceNode({
		name: 'Инфраструктура обеспечения площадок и параметров окружающей среды',
	  	id: 1118,
	  	parents: [1001, 1002, 1003, 1004, 1005, 1006],
	  	rtoTarget: 16,
  		rtoTest: 0,
	}),
	new ItResourceNode({
		name: 'Инфраструктура корпоративной локальной сети',
	  	id: 1119,
	  	parents: [1001, 1002, 1003, 1004, 1005, 1006],
	  	rtoTarget: 8,
  		rtoTest: 0,
	}),
	new ItResourceNode({
		name: 'Система резервного копирования данных',
	  	id: 1120,
	  	parents: [1001, 1002, 1003, 1004],
		rtoTarget: 8,
  		rtoTest: 0,
	}),
]
