name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest        
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14.x
                  cache: 'yarn'
            # Build
            - run: cd front && yarn --frozen-lockfile
            - run: cd front && yarn build
            # Deploy
            - uses: nekitcorp/yandex-storage-website-action@v1
              with:
                  accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
                  secretAccessKey: ${{ secrets.SECRET_ACCESS_KEY }}
                  bucket: ${{ secrets.BUCKET }}
                  path: "./front/build"
                  clear: true
